In [2]:
import numpy as np

# Create a 1D array

arr1 = np.array([1,2,3])

print(arr1)

[1 2 3]


In [3]:
# check the array

print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
# Check the shape of the array

print(arr1.shape)

(3,)


In [5]:
# accessing elements from the array

arr1[2]

3

In [6]:
# Change an element from the array

arr1[2]= 5

In [7]:
arr1

array([1, 2, 5])

In [8]:
# Create a 2D array

arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
# Check the shape of the array

print("The shape is 2 rows and 3 columns:", arr2.shape)

The shape is 2 rows and 3 columns: (2, 3)


In [10]:
# Accessing elements from the array

arr2[0][2]

3

In [11]:
arr2[0,2]

3

In [12]:
arr2[0,-2]

2

In [13]:
arr2[0,-1]

3

In [14]:
arr2[-1, 0]

4

In [15]:
# Array of type string

arr3 = np.array(['India', 'China', 'USA' , 'Mexico'])
print(arr3)

['India' 'China' 'USA' 'Mexico']


In [16]:
arr3[1]

'China'

In [17]:
# Array of evenly spaced values within a specified interval

arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [18]:
# Array of evenly spaced number in a specified interval

arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [19]:
# Array of random values between 0 and 1 in a given shape

arr = np.random.rand(10)
print(arr)
print('\n')
arr = np.random.rand(3,4)
print(arr)

[0.1392098  0.83698099 0.68316339 0.89007915 0.63360623 0.09798634
 0.79675009 0.4227871  0.7022205  0.42574999]


[[0.11266553 0.90551118 0.05616417 0.95122541]
 [0.93066177 0.95395431 0.21902002 0.05484626]
 [0.40629795 0.81374341 0.0976142  0.8474203 ]]


In [20]:
# Array of zeros

print(np.zeros(10))
print('\n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
# Array of constant values in a given shape

print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [23]:
# Create an array by repetition
# epeat each element of an array by a specified number of times

arr = [0, 1, 2]
print(np.repeat(arr, 3)) 

[0 0 0 1 1 1 2 2 2]


In [24]:
# Repeat an array by a specified number of times

arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [25]:
# Create an idenity matrix

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
# Create a matrix with a specified diagonal array

arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [28]:
arr = np.random.rand(5,5)
print(arr)

[[0.64369883 0.3601157  0.00429396 0.27151001 0.49048325]
 [0.03063554 0.80215512 0.87570363 0.95146256 0.02927559]
 [0.60124132 0.99773664 0.68247255 0.87779774 0.13177439]
 [0.42717673 0.29937041 0.44227719 0.22772854 0.36199309]
 [0.48954527 0.45206959 0.67265616 0.19287145 0.57323525]]


In [29]:
# Extract the diagonal elements in the array
print(np.diag(arr))

[0.64369883 0.80215512 0.68247255 0.22772854 0.57323525]


In [30]:
# Display the length of the array
print(len(arr))

5


In [31]:
# Display the dimension of the array
print(arr.ndim)

2


In [32]:
# Display the size of the elements
print(arr.size)

25


In [33]:
# print 4 random integers

print(np.random.randint(-10, 10, 4))

[ 7 -1 -4 -1]


In [34]:
# Mathematical operations

print(arr + 10)
print('\n')
print(arr - 10)
print('\n')
print(arr * 10)
print('\n')
print(arr / 10)

[[10.64369883 10.3601157  10.00429396 10.27151001 10.49048325]
 [10.03063554 10.80215512 10.87570363 10.95146256 10.02927559]
 [10.60124132 10.99773664 10.68247255 10.87779774 10.13177439]
 [10.42717673 10.29937041 10.44227719 10.22772854 10.36199309]
 [10.48954527 10.45206959 10.67265616 10.19287145 10.57323525]]


[[-9.35630117 -9.6398843  -9.99570604 -9.72848999 -9.50951675]
 [-9.96936446 -9.19784488 -9.12429637 -9.04853744 -9.97072441]
 [-9.39875868 -9.00226336 -9.31752745 -9.12220226 -9.86822561]
 [-9.57282327 -9.70062959 -9.55772281 -9.77227146 -9.63800691]
 [-9.51045473 -9.54793041 -9.32734384 -9.80712855 -9.42676475]]


[[6.4369883  3.60115698 0.04293959 2.71510011 4.90483246]
 [0.30635537 8.02155116 8.75703626 9.5146256  0.29275586]
 [6.01241323 9.97736644 6.8247255  8.77797743 1.31774391]
 [4.27176732 2.99370414 4.42277191 2.27728536 3.61993092]
 [4.89545275 4.52069587 6.72656164 1.92871448 5.73235255]]


[[0.06436988 0.03601157 0.0004294  0.027151   0.04904832]
 [0.00306355 

In [35]:
# Exponentiation

print(np.exp(arr))

[[1.90350863 1.43349526 1.00430319 1.31194401 1.63310522]
 [1.03110963 2.2303424  2.4005638  2.58949418 1.02970833]
 [1.82438204 2.71213635 1.97876428 2.40559613 1.1408509 ]
 [1.53292355 1.34900922 1.55624706 1.25574439 1.43618902]
 [1.63157413 1.5715613  1.959435   1.21272689 1.77399711]]


In [36]:
# Natural logarithm

print(np.log(arr))

[[-4.40524317e-01 -1.02132992e+00 -5.45054613e+00 -1.30375627e+00
  -7.12364157e-01]
 [-3.48559460e+00 -2.20453279e-01 -1.32727571e-01 -4.97549410e-02
  -3.53100134e+00]
 [-5.08758890e-01 -2.26592172e-03 -3.82032972e-01 -1.30339073e-01
  -2.02666398e+00]
 [-8.50557458e-01 -1.20607363e+00 -8.15818464e-01 -1.47960099e+00
  -1.01613015e+00]
 [-7.14278330e-01 -7.93919159e-01 -3.96520980e-01 -1.64573138e+00
  -5.56459080e-01]]


In [37]:
# Base 2 logarithm

print(np.log2(arr))

[[-6.35542248e-01 -1.47346761e+00 -7.86347587e+00 -1.88092270e+00
  -1.02772424e+00]
 [-5.02865004e+00 -3.18046852e-01 -1.91485409e-01 -7.17812067e-02
  -5.09415812e+00]
 [-7.33983927e-01 -3.26903402e-03 -5.51157074e-01 -1.88039534e-01
  -2.92385807e+00]
 [-1.22709503e+00 -1.73999645e+00 -1.17697725e+00 -2.13461301e+00
  -1.46596593e+00]
 [-1.03048580e+00 -1.14538323e+00 -5.72058852e-01 -2.37428850e+00
  -8.02800755e-01]]


In [38]:
# Base 10 logarithm

print(np.log10(arr))

[[-1.91317280e-01 -4.43557947e-01 -2.36714211e+00 -5.66214152e-01
  -3.09375822e-01]
 [-1.51377450e+00 -9.57416425e-02 -5.76428518e-02 -2.16082963e-02
  -1.53349440e+00]
 [-2.20951178e-01 -9.84077298e-04 -1.65914812e-01 -5.66055400e-02
  -8.80168983e-01]
 [-3.69392411e-01 -5.23791123e-01 -3.54305457e-01 -6.42582546e-01
  -4.41299717e-01]
 [-3.10207137e-01 -3.44794710e-01 -1.72206874e-01 -7.14732058e-01
  -2.41667108e-01]]


In [39]:
# sin function

print(np.sin(arr))

[[0.60015817 0.35238251 0.00429395 0.26818644 0.47105222]
 [0.03063075 0.71885591 0.76799433 0.81426538 0.0292714 ]
 [0.56566655 0.84024593 0.63071369 0.76933384 0.13139336]
 [0.41430289 0.29491868 0.42799865 0.22576529 0.35413886]
 [0.47022462 0.43682815 0.62306575 0.19167789 0.54235298]]


In [40]:
print(np.sin(180))

-0.8011526357338304


In [41]:
print(np.sin(0))

0.0


In [42]:
# cos function

print(np.cos(arr))

[[0.79988135 0.93585606 0.99999078 0.96336703 0.88210533]
 [0.99953077 0.69515911 0.64045664 0.5804928  0.9995715 ]
 [0.82463408 0.54220547 0.77601562 0.63884696 0.99133031]
 [0.91013906 0.95552236 0.90377937 0.97418173 0.93519285]
 [0.88254677 0.89954498 0.78216946 0.98145789 0.84015073]]


In [43]:
print(arr)

[[0.64369883 0.3601157  0.00429396 0.27151001 0.49048325]
 [0.03063554 0.80215512 0.87570363 0.95146256 0.02927559]
 [0.60124132 0.99773664 0.68247255 0.87779774 0.13177439]
 [0.42717673 0.29937041 0.44227719 0.22772854 0.36199309]
 [0.48954527 0.45206959 0.67265616 0.19287145 0.57323525]]


In [44]:
# sum along the row
print(np.sum(arr, axis=0))

[2.1922977  2.91144746 2.67740349 2.5213703  1.58676157]


In [45]:
# sum along the column
print(np.sum(arr, axis=1))

[1.77010174 2.68923243 3.29102265 1.75854597 2.38037773]


In [46]:
# minimum item value along the row
print(np.min(arr))

0.00429395898861451


In [47]:
print(np.max(arr))

0.9977366435465933


In [48]:
# calculate the overall mean

print(np.mean(arr))

0.475571220591915


In [49]:
# calculate the mean along the row

print(np.mean(arr, axis=0))

[0.43845954 0.58228949 0.5354807  0.50427406 0.31735231]


In [50]:
# calculate the median
print(np.median(arr))

0.4520695865285794


In [51]:
# calculate the standard deviation
print(np.std(arr))

0.2860109515708331


In [52]:
# calculate the variance
print(np.var(arr))

0.08180226441845344


In [53]:
print(arr)
print('\n')
print(arr[1:3, 2:5])

[[0.64369883 0.3601157  0.00429396 0.27151001 0.49048325]
 [0.03063554 0.80215512 0.87570363 0.95146256 0.02927559]
 [0.60124132 0.99773664 0.68247255 0.87779774 0.13177439]
 [0.42717673 0.29937041 0.44227719 0.22772854 0.36199309]
 [0.48954527 0.45206959 0.67265616 0.19287145 0.57323525]]


[[0.87570363 0.95146256 0.02927559]
 [0.68247255 0.87779774 0.13177439]]


In [54]:
# Sort an array
arr = np.random.rand(5,5)
print(arr)

[[0.55594777 0.84174885 0.28846287 0.75377413 0.91492807]
 [0.46812092 0.71379497 0.06691855 0.07251317 0.92087481]
 [0.74164069 0.6305517  0.35558005 0.53333519 0.86155643]
 [0.61148081 0.44481802 0.30491522 0.82357112 0.25428774]
 [0.0626613  0.77978402 0.47889787 0.99549768 0.31905657]]


In [55]:
# sort along the column

print(np.sort(arr, axis=1))

[[0.28846287 0.55594777 0.75377413 0.84174885 0.91492807]
 [0.06691855 0.07251317 0.46812092 0.71379497 0.92087481]
 [0.35558005 0.53333519 0.6305517  0.74164069 0.86155643]
 [0.25428774 0.30491522 0.44481802 0.61148081 0.82357112]
 [0.0626613  0.31905657 0.47889787 0.77978402 0.99549768]]


In [56]:
# Transpose an array
print(arr)
print('\n')
print(arr.T)

[[0.55594777 0.84174885 0.28846287 0.75377413 0.91492807]
 [0.46812092 0.71379497 0.06691855 0.07251317 0.92087481]
 [0.74164069 0.6305517  0.35558005 0.53333519 0.86155643]
 [0.61148081 0.44481802 0.30491522 0.82357112 0.25428774]
 [0.0626613  0.77978402 0.47889787 0.99549768 0.31905657]]


[[0.55594777 0.46812092 0.74164069 0.61148081 0.0626613 ]
 [0.84174885 0.71379497 0.6305517  0.44481802 0.77978402]
 [0.28846287 0.06691855 0.35558005 0.30491522 0.47889787]
 [0.75377413 0.07251317 0.53333519 0.82357112 0.99549768]
 [0.91492807 0.92087481 0.86155643 0.25428774 0.31905657]]


In [57]:
print(arr.transpose())

[[0.55594777 0.46812092 0.74164069 0.61148081 0.0626613 ]
 [0.84174885 0.71379497 0.6305517  0.44481802 0.77978402]
 [0.28846287 0.06691855 0.35558005 0.30491522 0.47889787]
 [0.75377413 0.07251317 0.53333519 0.82357112 0.99549768]
 [0.91492807 0.92087481 0.86155643 0.25428774 0.31905657]]


In [58]:
# Flatten the 2D array

print(arr)
print('\n')
print(arr.flatten())

[[0.55594777 0.84174885 0.28846287 0.75377413 0.91492807]
 [0.46812092 0.71379497 0.06691855 0.07251317 0.92087481]
 [0.74164069 0.6305517  0.35558005 0.53333519 0.86155643]
 [0.61148081 0.44481802 0.30491522 0.82357112 0.25428774]
 [0.0626613  0.77978402 0.47889787 0.99549768 0.31905657]]


[0.55594777 0.84174885 0.28846287 0.75377413 0.91492807 0.46812092
 0.71379497 0.06691855 0.07251317 0.92087481 0.74164069 0.6305517
 0.35558005 0.53333519 0.86155643 0.61148081 0.44481802 0.30491522
 0.82357112 0.25428774 0.0626613  0.77978402 0.47889787 0.99549768
 0.31905657]


In [59]:
# Append elements to an array

arr = np.array([4,5,6,7])

In [60]:
arr1 = np.append(arr, 8)
arr1

array([4, 5, 6, 7, 8])

In [61]:
arr2 = np.append(arr, [9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [62]:
# Insert elements to an array

arr3 = np.insert(arr, 0, [12,13,14])
print(arr3)

[12 13 14  4  5  6  7]


In [63]:
# Remove elements from an array

print(arr)
print('\n')
arr4 = np.delete(arr, 0)
print(arr4)

[4 5 6 7]


[5 6 7]


In [64]:
# Delete multiple elements

print(arr2)
print('\n')
arr5 = np.delete(arr2, [1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [65]:
# Copy elements from an array

arr1 = np.arange(10, 40, 3)
arr1

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [66]:
arr_copy = np.copy(arr1)
arr_copy

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [67]:
arr_copy = arr1.copy()
print(arr_copy)

[10 13 16 19 22 25 28 31 34 37]


In [68]:
# Combine and split an array

arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [69]:
# Combine the array items by row

cat = np.concatenate((arr1,arr2), axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [70]:
# Combine array items by column

cat = np. concatenate((arr1, arr2), axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [71]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [72]:
# Stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [73]:
# Set operations

# Find elements from an array
arr = np.array([1,2,3,4,5,6,3,6,1,2,4])
print(np.unique(arr))

[1 2 3 4 5 6]


In [74]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


In [75]:
# Intersection of 2 array elements

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [76]:
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [77]:
# Union of 2 array elements

print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


In [78]:
# Elements present in first array but not in the second array
print(np.setdiff1d(arr1, arr2))
print(np.setdiff1d(arr2, arr1))

[1 2]
[6 7]


In [79]:
# Elements present in either of the arrays but not both

print(np.setxor1d(arr1, arr2))

[1 2 6 7]
